const products = [
  {
    _id: "1",
    slug: "ultimate-snack-box",
    name: "Ultimate Snack Box",
    shortDescription: "12 delicious healthy snacks combo",
    category: "Healthy Snacks",
    salePrice: 749,
    mrp: 838,
    rating: 4.5,
    stock: 0,
    isBestSeller: true,
    images: ["/products/product1.webp"],
  },
  {
    _id: "2",
    slug: "assorted-laddoo-box",
    name: "Assorted Laddoo Box",
    shortDescription: "24 laddoos in 6 delicious flavours",
    category: "Sweetened With Dates",
    salePrice: 349,
    mrp: 394,
    rating: 4.2,
    stock: 4,
    isBestSeller: false,
    images: ["/products/product1.webp"],
  },
  {
    _id: "3",
    slug: "millet-namkeen-combo",
    name: "Assorted Namkeen Combo",
    shortDescription: "Roasted crunchy millet namkeen combo",
    category: "No Palm Oil",
    salePrice: 269,
    mrp: 276,
    rating: 3.7,
    stock: 18,
    isBestSeller: false,
    images: ["/products/product1.webp"],
  },
  {
    _id: "4",
    slug: "dry-fruit-laddoo-box",
    name: "Dry Fruit Laddoo Box",
    shortDescription: "42 premium dry-fruit laddoos",
    category: "Sweetened With Dates",
    salePrice: 649,
    mrp: 694,
    rating: 4.6,
    stock: 2,
    isBestSeller: false,
    images: ["/products/product1.webp"],
  },
  {
    _id: "5",
    slug: "protein-mix",
    name: "Protein Snack Mix",
    shortDescription: "High protein healthy snack mix",
    category: "Protein Rich",
    salePrice: 299,
    mrp: 349,
    rating: 4.3,
    stock: 30,
    isBestSeller: true,
    images: ["/products/product1.webp"],
  },
  {
    _id: "6",
    slug: "roasted-makhana",
    name: "Roasted Makhana",
    shortDescription: "Crunchy roasted fox nuts",
    category: "Healthy Snacks",
    salePrice: 199,
    mrp: 249,
    rating: 4.4,
    stock: 15,
    isBestSeller: false,
    images: ["/products/product1.webp"],
  },
  {
    _id: "7",
    slug: "almond-dates-bar",
    name: "Almond Dates Bar",
    shortDescription: "Natural energy snack bar",
    category: "Energy Bars",
    salePrice: 149,
    mrp: 179,
    rating: 4.1,
    stock: 8,
    isBestSeller: false,
    images: ["/products/product1.webp"],
  },
  {
    _id: "8",
    slug: "fruit-nut-mix",
    name: "Fruit & Nut Mix",
    shortDescription: "Premium dry fruits and berries",
    category: "Dry Fruits",
    salePrice: 499,
    mrp: 599,
    rating: 4.8,
    stock: 20,
    isBestSeller: true,
    images: ["/products/product1.webp"],
  },
  {
    _id: "9",
    slug: "multigrain-chips",
    name: "Multigrain Chips",
    shortDescription: "Baked multigrain crunchy chips",
    category: "Healthy Snacks",
    salePrice: 179,
    mrp: 199,
    rating: 4.0,
    stock: 1,
    isBestSeller: false,
    images: ["/products/product1.webp"],
  },
  {
    _id: "10",
    slug: "choco-date-bites",
    name: "Choco Date Bites",
    shortDescription: "Chocolate coated date bites",
    category: "Sweetened With Dates",
    salePrice: 259,
    mrp: 299,
    rating: 4.5,
    stock: 12,
    isBestSeller: false,
    images: ["/products/product1.webp"],
  },
  {
    _id: "11",
    slug: "healthy-breakfast-pack",
    name: "Healthy Breakfast Pack",
    shortDescription: "Breakfast combo with granola",
    category: "Breakfast",
    salePrice: 549,
    mrp: 649,
    rating: 4.7,
    stock: 5,
    isBestSeller: true,
    images: ["/products/product1.webp"],
  },
  {
    _id: "12",
    slug: "premium-gift-box",
    name: "Premium Gift Box",
    shortDescription: "Luxury gifting hamper",
    category: "Gift Box",
    salePrice: 999,
    mrp: 1199,
    rating: 4.9,
    stock: 25,
    isBestSeller: true,
    images: ["/products/product1.webp"],
  },
];

export default products;